sudo: required
dist: trusty

# travis-ci does not have first-class support for octave
language: python

matrix:
  include:
    - env: OCT_PPA=no
      addons:
        apt:
          packages:
            - octave
            - liboctave-dev
    - env: OCT_PPA=yes

install:
  - export
  - if [ "x$OCT_PPA" = "xyes" ]; then
        sudo apt-add-repository -y ppa:octave/stable;
        sudo apt-get update -qq;
        sudo apt-get install -qq -y octave liboctave-dev;
    fi

script: make test test-interactive
