dist: xenial
language: generic

services:
- docker

matrix:
  include:
  - name: "Octave version 4.2"
    env: TAG=4.2
  - name: "Octave version 4.4"
    env: TAG=4.4
  - name: "Octave version 5"
    env: TAG=5

before_install:
- docker pull mtmiller/octave:${TAG}

script:
- docker run --volume=${PWD}:/doctest:z mtmiller/octave:${TAG} make -C /doctest test test-interactive test-bist
