sudo: required
dist: trusty

# travis-ci does not have first-class support for octave
language: generic

addons:
  apt:
    sources:
    - sourceline: 'ppa:octave/stable'
    # not on trusty: http://ppa.launchpad.net/dac922/octave-unstable/ubuntu/pool/main/o/octave/
    # - sourceline: 'ppa:dac922/octave-unstable'
    packages:
    - octave
    - liboctave-dev

script: make test test-interactive
