dist: xenial
language: generic

services:
  - docker

matrix:
  include:
  - name: "Octave latest release"
    env: IMAGE_TAG=latest

before_install:
  - docker pull mtmiller/octave:${IMAGE_TAG}

script:
  - docker run --volume=${PWD}:/doctest mtmiller/octave:${IMAGE_TAG} make -C /doctest test test-interactive
