dist: xenial
language: generic

services:
- docker

matrix:
  include:
  - name: "Octave latest release"
    env: TAG=latest

before_install:
- docker pull mtmiller/octave:${TAG}

script:
- docker run --volume=${PWD}:/doctest:z mtmiller/octave:${TAG} make -C /doctest test test-interactive test-bist
