sudo: required
dist: trusty

# travis-ci does not have first-class support for octave
language: generic

env:
- OCT_PPA=octave/stable

# not on trusty: http://ppa.launchpad.net/dac922/octave-unstable/ubuntu/pool/main/o/octave/
#- OCT_PPA=dac922/octave-unstable

install:
  - export
  - if [ "x$OCT_PPA" != "x" ]; then
        sudo apt-add-repository -y ppa:$OCT_PPA;
        sudo apt-get update -qq;
        sudo apt-get install -qq -y octave liboctave-dev;
    fi

script: make test test-interactive
